import {
  FeatureFlag,
  CriticalLevel,
  LogType,
  FeatureFlagConfig,
  AlertConfig,
  AlertSeverity,
  DashboardComponent,
  BuildType
} from './types';

// Feature Flag Configurations
export const FEATURE_FLAG_CONFIGS: Record<FeatureFlag, Omit<FeatureFlagConfig, 'enabled'>> = {
  [FeatureFlag.ENV_DEVELOPMENT]: {
    flag: FeatureFlag.ENV_DEVELOPMENT,
    criticalLevel: CriticalLevel.CRITICAL,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '🌍 DEV',
    badgeDisabled: '🌍 PROD',
    buildTimeImpact: '+15% size',
  },
  [FeatureFlag.ENV_PRODUCTION]: {
    flag: FeatureFlag.ENV_PRODUCTION,
    criticalLevel: CriticalLevel.CRITICAL,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '🌍 PROD',
    badgeDisabled: '🌍 DEV',
    buildTimeImpact: '-25% size',
  },
  [FeatureFlag.FEAT_PREMIUM]: {
    flag: FeatureFlag.FEAT_PREMIUM,
    criticalLevel: CriticalLevel.HIGH,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '🏆 PREMIUM',
    badgeDisabled: '🔓 FREE',
    buildTimeImpact: '+15% size',
    memoryImpact: '+15%',
    cpuImpact: '+5%',
    bundleSizeImpact: '+12%',
    startupTimeImpact: '+200ms',
  },
  [FeatureFlag.FEAT_AUTO_HEAL]: {
    flag: FeatureFlag.FEAT_AUTO_HEAL,
    criticalLevel: CriticalLevel.HIGH,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '🔄 AUTO-HEAL',
    badgeDisabled: '⚠️ MANUAL',
    buildTimeImpact: '+10% size',
    memoryImpact: '+8%',
    cpuImpact: '+3%',
    bundleSizeImpact: '+10%',
    startupTimeImpact: '+150ms',
  },
  [FeatureFlag.FEAT_NOTIFICATIONS]: {
    flag: FeatureFlag.FEAT_NOTIFICATIONS,
    criticalLevel: CriticalLevel.MEDIUM,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '🔔 ACTIVE',
    badgeDisabled: '🔕 SILENT',
    buildTimeImpact: '+8% size',
    memoryImpact: '+3%',
    cpuImpact: '+2%',
    bundleSizeImpact: '+8%',
    startupTimeImpact: '+50ms',
  },
  [FeatureFlag.FEAT_ENCRYPTION]: {
    flag: FeatureFlag.FEAT_ENCRYPTION,
    criticalLevel: CriticalLevel.CRITICAL,
    logHook: LogType.SECURITY_EVENT,
    badgeEnabled: '🔐 ENCRYPTED',
    badgeDisabled: '⚠️ PLAINTEXT',
    buildTimeImpact: '+5% size',
    memoryImpact: '+10%',
    cpuImpact: '+8%',
    bundleSizeImpact: '+5%',
    startupTimeImpact: '+300ms',
  },
  [FeatureFlag.FEAT_MOCK_API]: {
    flag: FeatureFlag.FEAT_MOCK_API,
    criticalLevel: CriticalLevel.PROD_CRITICAL,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '🧪 MOCK',
    badgeDisabled: '🚀 REAL',
    buildTimeImpact: '-20% size',
    memoryImpact: '-30%',
    cpuImpact: '-40%',
    bundleSizeImpact: '-20%',
    startupTimeImpact: '-100ms',
  },
  [FeatureFlag.FEAT_EXTENDED_LOGGING]: {
    flag: FeatureFlag.FEAT_EXTENDED_LOGGING,
    criticalLevel: CriticalLevel.LOW,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '📝 VERBOSE',
    badgeDisabled: '📋 NORMAL',
    buildTimeImpact: '+12% size',
    memoryImpact: '+15%',
    cpuImpact: '+5%',
    bundleSizeImpact: '+12%',
    startupTimeImpact: '+200ms',
  },
  [FeatureFlag.FEAT_ADVANCED_MONITORING]: {
    flag: FeatureFlag.FEAT_ADVANCED_MONITORING,
    criticalLevel: CriticalLevel.MEDIUM,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '📈 ADVANCED',
    badgeDisabled: '📊 BASIC',
    buildTimeImpact: '+7% size',
    memoryImpact: '+25%',
    cpuImpact: '+10%',
    bundleSizeImpact: '+7%',
    startupTimeImpact: '+500ms',
  },
  [FeatureFlag.FEAT_BATCH_PROCESSING]: {
    flag: FeatureFlag.FEAT_BATCH_PROCESSING,
    criticalLevel: CriticalLevel.LOW,
    logHook: LogType.PERFORMANCE_METRIC,
    badgeEnabled: '⚡ BATCH',
    badgeDisabled: '🐌 SEQUENTIAL',
    buildTimeImpact: '+8% size',
    memoryImpact: '+5%',
    cpuImpact: '-20%',
    bundleSizeImpact: '+8%',
    startupTimeImpact: '+100ms',
  },
  [FeatureFlag.FEAT_VALIDATION_STRICT]: {
    flag: FeatureFlag.FEAT_VALIDATION_STRICT,
    criticalLevel: CriticalLevel.HIGH,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '✅ STRICT',
    badgeDisabled: '⚠️ LENIENT',
    buildTimeImpact: '+5% size',
    memoryImpact: '+5%',
    cpuImpact: '+3%',
    bundleSizeImpact: '+5%',
    startupTimeImpact: '+100ms',
  },
  [FeatureFlag.PLATFORM_ANDROID]: {
    flag: FeatureFlag.PLATFORM_ANDROID,
    criticalLevel: CriticalLevel.CRITICAL,
    logHook: LogType.FEATURE_CHANGE,
    badgeEnabled: '🤖 ANDROID',
    badgeDisabled: '🍎 IOS',
    buildTimeImpact: '+10% size',
  },
  [FeatureFlag.INTEGRATION_GEELARK_API]: {
    flag: FeatureFlag.INTEGRATION_GEELARK_API,
    criticalLevel: CriticalLevel.CRITICAL,
    logHook: LogType.INTEGRATION_EVENT,
    badgeEnabled: '🔌 GEELARK API',
    badgeDisabled: '🔌 NO API',
    buildTimeImpact: '+20% size',
  },
  [FeatureFlag.INTEGRATION_PROXY_SERVICE]: {
    flag: FeatureFlag.INTEGRATION_PROXY_SERVICE,
    criticalLevel: CriticalLevel.MEDIUM,
    logHook: LogType.INTEGRATION_EVENT,
    badgeEnabled: '🌐 PROXY',
    badgeDisabled: '🚫 NO PROXY',
    buildTimeImpact: '+5% size',
  },
  [FeatureFlag.INTEGRATION_EMAIL_SERVICE]: {
    flag: FeatureFlag.INTEGRATION_EMAIL_SERVICE,
    criticalLevel: CriticalLevel.MEDIUM,
    logHook: LogType.INTEGRATION_EVENT,
    badgeEnabled: '📧 EMAIL',
    badgeDisabled: '🚫 NO EMAIL',
    buildTimeImpact: '+3% size',
  },
  [FeatureFlag.INTEGRATION_SMS_SERVICE]: {
    flag: FeatureFlag.INTEGRATION_SMS_SERVICE,
    criticalLevel: CriticalLevel.MEDIUM,
    logHook: LogType.INTEGRATION_EVENT,
    badgeEnabled: '💬 SMS',
    badgeDisabled: '🚫 NO SMS',
    buildTimeImpact: '+3% size',
  },
};

// Alert Configurations
export const ALERT_CONFIGS: AlertConfig[] = [
  {
    type: 'Security Critical',
    triggerCondition: `${FeatureFlag.FEAT_ENCRYPTION} disabled in production`,
    severity: AlertSeverity.CRITICAL,
    notificationChannels: ['SMS', 'Email', 'Slack', 'PagerDuty'],
    responseTime: 'Immediate',
    autoRecovery: false,
    escalationPath: 'Security Team',
  },
  {
    type: 'Production Warning',
    triggerCondition: `${FeatureFlag.FEAT_MOCK_API} enabled in production`,
    severity: AlertSeverity.HIGH,
    notificationChannels: ['Email', 'Slack'],
    responseTime: '15 minutes',
    autoRecovery: true,
    escalationPath: 'DevOps Team',
  },
  {
    type: 'Feature Degradation',
    triggerCondition: '>30% features disabled',
    severity: AlertSeverity.MEDIUM,
    notificationChannels: ['Slack', 'Dashboard'],
    responseTime: '1 hour',
    autoRecovery: true,
    escalationPath: 'Development Team',
  },
  {
    type: 'Integration Failure',
    triggerCondition: `INTEGRATION_* service down >5min`,
    severity: AlertSeverity.MEDIUM,
    notificationChannels: ['Email', 'Slack'],
    responseTime: '30 minutes',
    autoRecovery: true,
    escalationPath: 'Integration Team',
  },
  {
    type: 'Performance Alert',
    triggerCondition: `${FeatureFlag.FEAT_BATCH_PROCESSING} disabled at scale`,
    severity: AlertSeverity.MEDIUM,
    notificationChannels: ['Dashboard only'],
    responseTime: '2 hours',
    autoRecovery: false,
    escalationPath: 'Performance Team',
  },
  {
    type: 'Monitoring Gap',
    triggerCondition: `${FeatureFlag.FEAT_ADVANCED_MONITORING} disabled`,
    severity: AlertSeverity.LOW,
    notificationChannels: ['Dashboard only'],
    responseTime: '4 hours',
    autoRecovery: false,
    escalationPath: 'Monitoring Team',
  },
];

// Dashboard Components
export const DASHBOARD_COMPONENTS: DashboardComponent[] = [
  {
    name: 'Top Status Bar',
    displayType: 'Text + Emoji',
    updateFrequency: 'Real-time',
    dataSource: 'Feature Registry',
    widthCalculation: 'Bun.stringWidth()',
    ansiSupport: true,
    exportFormats: ['JSON', 'TEXT'],
  },
  {
    name: 'Environment Panel',
    displayType: 'Badge Grid',
    updateFrequency: 'On-change',
    dataSource: 'ENV_* flags',
    widthCalculation: 'Grapheme-aware',
    ansiSupport: true,
    exportFormats: ['JSON', 'CSV'],
  },
  {
    name: 'Feature Tier Display',
    displayType: 'Large Badge',
    updateFrequency: 'Static',
    dataSource: FeatureFlag.FEAT_PREMIUM,
    widthCalculation: 'Emoji + ZWJ support',
    ansiSupport: true,
    exportFormats: ['JSON'],
  },
  {
    name: 'Security Status',
    displayType: 'Color-coded',
    updateFrequency: 'Real-time',
    dataSource: 'Security flags',
    widthCalculation: 'Zero-width aware',
    ansiSupport: true,
    exportFormats: ['JSON', 'PDF'],
  },
  {
    name: 'Resilience Monitor',
    displayType: 'Icon + Status',
    updateFrequency: '5 seconds',
    dataSource: 'Auto-heal metrics',
    widthCalculation: 'ANSI sequence aware',
    ansiSupport: true,
    exportFormats: ['JSON'],
  },
  {
    name: 'Notification Panel',
    displayType: 'Live List',
    updateFrequency: '1 second',
    dataSource: 'Notification queue',
    widthCalculation: 'Full Unicode',
    ansiSupport: true,
    exportFormats: ['JSON', 'HTML'],
  },
  {
    name: 'Performance Graph',
    displayType: 'ASCII/Unicode',
    updateFrequency: '2 seconds',
    dataSource: 'Performance metrics',
    widthCalculation: 'East Asian width',
    ansiSupport: true,
    exportFormats: ['PNG', 'CSV'],
  },
  {
    name: 'Log Viewer',
    displayType: 'Scrolling Text',
    updateFrequency: 'User action',
    dataSource: 'Log buffer',
    widthCalculation: 'Proper wrapping',
    ansiSupport: true,
    exportFormats: ['LOG', 'JSON'],
  },
  {
    name: 'Integration Grid',
    displayType: 'Service Icons',
    updateFrequency: '30 seconds',
    dataSource: 'Health checks',
    widthCalculation: 'Emoji flag support',
    ansiSupport: true,
    exportFormats: ['JSON', 'CSV'],
  },
];

// Build Configurations
export const BUILD_CONFIGS: Record<BuildType, {
  flags: FeatureFlag[];
  bundleSize: string;
  deadCodePercent: string;
  minify: boolean;
  useCase: string;
}> = {
  [BuildType.DEVELOPMENT]: {
    flags: [FeatureFlag.ENV_DEVELOPMENT, FeatureFlag.FEAT_EXTENDED_LOGGING, FeatureFlag.FEAT_MOCK_API],
    bundleSize: '450KB',
    deadCodePercent: '0%',
    minify: false,
    useCase: 'Local Development',
  },
  [BuildType.PRODUCTION_LITE]: {
    flags: [FeatureFlag.ENV_PRODUCTION, FeatureFlag.FEAT_ENCRYPTION],
    bundleSize: '320KB',
    deadCodePercent: '29%',
    minify: true,
    useCase: 'Minimal Deployment',
  },
  [BuildType.PRODUCTION_STANDARD]: {
    flags: [
      FeatureFlag.ENV_PRODUCTION,
      FeatureFlag.FEAT_AUTO_HEAL,
      FeatureFlag.FEAT_NOTIFICATIONS,
      FeatureFlag.FEAT_ENCRYPTION,
      FeatureFlag.FEAT_BATCH_PROCESSING,
    ],
    bundleSize: '280KB',
    deadCodePercent: '38%',
    minify: true,
    useCase: 'Standard Deployment',
  },
  [BuildType.PRODUCTION_PREMIUM]: {
    flags: [
      FeatureFlag.ENV_PRODUCTION,
      FeatureFlag.FEAT_PREMIUM,
      FeatureFlag.FEAT_AUTO_HEAL,
      FeatureFlag.FEAT_NOTIFICATIONS,
      FeatureFlag.FEAT_ENCRYPTION,
      FeatureFlag.FEAT_BATCH_PROCESSING,
      FeatureFlag.FEAT_ADVANCED_MONITORING,
      FeatureFlag.FEAT_EXTENDED_LOGGING,
      FeatureFlag.FEAT_VALIDATION_STRICT,
    ],
    bundleSize: '340KB',
    deadCodePercent: '24%',
    minify: true,
    useCase: 'Premium Deployment',
  },
  [BuildType.TEST]: {
    flags: [FeatureFlag.ENV_DEVELOPMENT, FeatureFlag.FEAT_MOCK_API],
    bundleSize: '180KB',
    deadCodePercent: '60%',
    minify: false,
    useCase: 'CI/CD Testing',
  },
  [BuildType.AUDIT]: {
    flags: [
      FeatureFlag.ENV_DEVELOPMENT,
      FeatureFlag.FEAT_PREMIUM,
      FeatureFlag.FEAT_AUTO_HEAL,
      FeatureFlag.FEAT_NOTIFICATIONS,
      FeatureFlag.FEAT_ENCRYPTION,
      FeatureFlag.FEAT_BATCH_PROCESSING,
      FeatureFlag.FEAT_ADVANCED_MONITORING,
      FeatureFlag.FEAT_EXTENDED_LOGGING,
      FeatureFlag.FEAT_VALIDATION_STRICT,
    ],
    bundleSize: '600KB',
    deadCodePercent: '0%',
    minify: false,
    useCase: 'Security Audit',
  },
};